# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JinRong' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JinRong
  pod 'SnapKit', '~> 3.2.0'
  pod 'NVActivityIndicatorView', '~> 3.6.1'
  pod 'Alamofire', '~> 4.5.0'
  pod 'ObjectMapper', '~> 2.2.8'
  pod 'PKHUD', '~> 4.2.3'
  pod 'DGElasticPullToRefresh', '~> 1.1'
  
  target 'JinRongTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JinRongUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
